---

services:
  algorithm-exercises-java:
    image: algorithm-exercises-java:latest
    build:
      context: .
      target: testing
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
      BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./build:/app/build
    profiles: [testing]

  algorithm-exercises-java-lint:
    image: algorithm-exercises-ts:lint
    build:
      context: .
      target: lint
    # environment:
    #   LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
    #   BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./:/app
    profiles: [lint]

  algorithm-exercises-java-dev:
    image: algorithm-exercises-java:dev
    build:
      context: .
      target: development
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
      BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./:/app
    profiles: [development]

## REFERENCES:
## (1) Passing Environment variable with fallback value:
##    https://stackoverflow.com/a/70772707/6366150
##
