// CHECKSTYLE.OFF: JavadocParagraph
/**
 * Even Fibonacci numbers
 *
 * https://projecteuler.net/problem=2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

package projecteuler;

import java.util.logging.Logger;

/**
 * Even Fibonacci numbers.
 */
public class Problem0002 {

  static Logger logger = projecteuler.util.CustomLogger.getLogger();

  /**
   * Problem template method.
   */
  public static Integer problem0002(int top) {

    int i = 0;
    int last1 = 1;
    int last2 = 0;
    int evenSum = 0;

    int fibo = 0;
    do {
      fibo = last2 + last1;

      logger.fine(String.format("Fibonacci(%d) = %d", i, fibo));

      if (fibo % 2 == 0) {
        evenSum += fibo;
      }

      // next keys:
      last2 = last1;
      last1 = fibo;
      i += 1;
    } while (fibo < top);

    logger.info(String.format("Problem 0002 result: %d", evenSum));

    return evenSum;
  }

}

//CHECKSTYLE.ON: JavadocParagraph
