// CHECKSTYLE.OFF: JavadocParagraph

package projecteuler;

/**
 * Even Fibonacci numbers
 *
 * https://projecteuler.net/problem=2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Problem0002 {

  /**
   * Problem template method.
   */
  public Integer problem0002(int top) {

    // int i = 0;
    int last1 = 1;
    int last2 = 0;
    int evenSum = 0;

    int fibo = 0;
    do {
      fibo = last2 + last1;

      // logger.debug(`Fibonacci (${i}) = ${fibo}`);

      if (fibo % 2 == 0) {
        evenSum += fibo;
      }

      // next keys:
      last2 = last1;
      last1 = fibo;
      //i += 1;
    } while (fibo < top);

    // logger.info(`RESULT = ${evenSum}`);
    return evenSum;
  }

}

//CHECKSTYLE.ON: JavadocParagraph
